# -*- encoding : utf-8 -*-

basepath = 'elements'

files = [

  'head/base/base_interface',
  'head/base',
  'head/link/link_interface',
  'head/link',
  'head/meta/meta_interface',
  'head/meta',
  'head/script/script_interface',
  'head/script',
  'head/style/style_interface',
  'head/style',
  'head/title/title_interface',
  'head/title',
  'head',
  
  'body/body_interface',
  'body',
  'anchor/anchor_interface',
  'anchor',
  'page_anchor/page_anchor_interface',
  'page_anchor',
  'button/button_interface',
  'button',
  'comment/comment_interface',
  'comment',
  'div/div_interface',
  'div',

  'hr',
  'image/image_interface',
  'image',

  'mail_to/mail_to_interface',
  'mail_to',

  'list/item',
  'list/ordered_list/ordered_list_interface',
  'list/ordered_list',
  'list/unordered_list',

  'table/row/header',
  'table/row/data',
  'table/row',
  'table/header_row',
  'table',

  'text/h1',
  'text/h2',
  'text/h3',
  'text/h4',
  'text/h5',
  'text/h6',
  'text/paragraph',
  'text/span',
  'text/date',

  'form/input',
  'form/input/button_input/button_input_interface',
  'form/input/button_input',
  'form/input/checkbox_input/checkbox_input_interface',
  'form/input/checkbox_input',
  'form/input/color_input/color_input_interface',
  'form/input/color_input',
  'form/input/data_list_input/data_list_input_interface',
  'form/input/data_list_input',
  'form/input/date_input/date_input_interface',
  'form/input/date_input',
  'form/input/date_time_input/date_time_input_interface',
  'form/input/date_time_input',
  'form/input/email_input/email_input_interface',
  'form/input/email_input',
  'form/input/input_error/input_error_interface',
  'form/input/input_error',
  'form/input/file_upload_input/file_upload_input_interface',
  'form/input/file_upload_input',
  'form/input/hidden_input/hidden_input_interface',
  'form/input/hidden_input',
  'form/input/input_label/input_label_interface',
  'form/input/input_label',
  'form/input/month_input/month_input_interface',
  'form/input/month_input',
  'form/input/number_input/number_input_interface',
  'form/input/number_input',
  'form/input/password_input/password_input_interface',
  'form/input/password_input',
  'form/input/radio_input/radio_input_interface',
  'form/input/radio_input',
  'form/input/range_input/range_input_interface',
  'form/input/range_input',
  'form/input/reset_input/reset_input_interface',
  'form/input/reset_input',
  'form/input/search_input/search_input_interface',
  'form/input/search_input',
  'form/input/select_input/select_input_interface',
  'form/input/select_input',
  'form/input/select_input/option_input/option_input_interface',
  'form/input/select_input/option_input',
  'form/input/submit_button/submit_button_interface',
  'form/input/submit_button',
  'form/input/telephone_input/telephone_input_interface',
  'form/input/telephone_input',
  'form/input/text_input/text_input_interface',
  'form/input/text_input',
  'form/input/text_input/text_area_input',
  'form/input/time_input/time_input_interface',
  'form/input/time_input',
  'form/input/url_input/url_input_interface',
  'form/input/url_input',
  'form/input/week_input/week_input_interface',
  'form/input/week_input',
  'form/form_interface',
  'form',
  
  'html/html_interface',
  'html'
  
]

files.each do |this_file|
  require_relative( File.join( basepath, this_file ) + '.rb' )
end
